name = "Neomanila"
author = "erik@gaius.red"
version = "0.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e45a627f27204a35450fb1efa5491477cfea09dc7ba9644d0cd50687c364cadd"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
