name = "Neomanila"
author = "erik@gaius.red"
version = "0.6.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9af1b33a55906b81a30bb43b4dea1b6de72d2f4417bc1989744a082482eee87d"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
