name = "Neomanila"
author = "erik@gaius.red"
version = "0.6.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec7307260f93de42c4f2495c65888e8974e8e2aae66aaf281fe3867e739c274a"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
