name = "Neomanila"
author = "erik@gaius.red"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d611cfa788d49618c2413a67178deb24b4d0a54734b52d63bc9e63aa0154895"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
