name = "Neomanila"
author = "erik@gaius.red"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea1996c95f6aca78d58d07566e735a5308ea5d794a3f7371b0f8083f44334189"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
