name = "Neomanila"
author = "erik@gaius.red"
version = "0.6.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe63e5ee7a578ecb08dd4d6847b48ae1927e2cd1a35c7d3c96f2f0b19bd7c734"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
