name = "Neomanila"
author = "erik@gaius.red"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f9e7566032aaaf3def709ea460be046fea3d089ca4af5e22bbee059436e5075"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
