name = "Neomanila"
author = "erik@gaius.red"
version = "0.6.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c80d8b40cc64ba9ab03b44ac581ade892037186359b5095488bd82cc424c30f7"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
