name = "Neomanila"
author = "erik@gaius.red"
version = "0.5.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eea473407d5c5ec3cf165347efe0aecb27e1d7d1ef940d7bd3b1036b1d057057"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
